### ISSUE TITLE
dots formatting broken in v0.4.1

### ISSUE THREAD

**Issue by jonasdebeukelaer** [gotestyourself/gotestsum#88]
Upgrading to v0.4.1 has broken `dots` formatting.
It's now printing out a huge amount of output like this:
```
    🖴  internal/pkg/jwt ·······
    🖴  internal/pkg/random ·
    🖴  internal/pkg/httputil ···············
    🖴  internal/pkg/retry ···
    🖴  internal/migrator ··
    🖴  internal/api/audit ·········
    🖴  internal/blah··········································
```

command used:
```bash
gotestsum --format dots ./...
```

platform: OSX 10.15.1

Cheers

**Comment by jonasdebeukelaer** [comment]
probably this is not actually clearing the whole output
https://github.com/gotestyourself/gotestsum/commit/aaff263ae35a76ea10a3d1b00d8744a00b2db07c#diff-45b6d30fedfbc737e332db2eca922536

I now see the newlines are intended, which is a shame as I liked the compactness of it previously.

**Comment by dnephin** [comment]
Thanks for the report! I meant to keep a format for the original version of `dots`, but it looks like I forgot. Sorry about that!

#89 adds a `dots-compact` option which is the original `dots` format.

**Comment by jonasdebeukelaer** [comment]
@dnephin good to hear! 

I think there's still an issue with the output of `dots` though. I understand it's now meant to print on a new line for each package, but it's creating thousands on lines of duplicate output, where it should only be about 100. I think stdout isn't being cleared properly after each update to the output.

**Comment by dnephin** [comment]
That sounds right. It was difficult to get the line counting exactly right, and I guess it doesn't work perfectly in other environments. Can you tell me more about your environment? Which OS, go version, terminal, and shell are you using? Are there any unicode characters or ansi color codes in the output? I thought I had accounted for all the unicode characters and ansi color codes, but I may have missed something.

I've tested on linux, go1.13, gnome-terminal, and bash.  

I updated #89 to add some leading new lines as a header. I'm not sure if that will fix anything. Are you able to try it out?

**Comment by jonasdebeukelaer** [comment]
hey sorry missed this notification!

I'm on macOS 10.15.1, `go1.13.4 darwin/amd64`, term2  and using zsh.
No the output is exactly as shown about, with the squares.

I'll try it out tomorrow!

**Comment by jonasdebeukelaer** [comment]
@dnephin dumb question but how do I run it from the git repo? Getting errors
```
./main.go:115:32: undefined: noSummaryValue
./main.go:116:32: undefined: junitFieldFormatValue
./main.go:117:32: undefined: junitFieldFormatValue
```

when running `go run/build main.go`

**Comment by dnephin** [comment]
```
go build -o gotestsum .
```

I think if you specify just the name of the file it uses only that file

**Comment by jonasdebeukelaer** [comment]
hey sorry for the slowness - yes your latest commit has returned it back to normal for me 👍

**Comment by dnephin** [comment]
Awesome! I think there is probably still more work to do, to get the dots-v2 format working in all environments. I'm going to close this issue and track that work separately.
